application: megaera-demo
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: .*
  script: main.application

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"
